#!/bin/bash

install_mac_os() {
    # 安装 Homebrew
    if [ ! `which brew` ]
    then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    # GNU coreutils
    brew install coreutils

}

install_ubuntu() {
    sudo apt-get update 2>> err.log
    # git
    sudo apt-get install -y git 2>> err.log
    sudo apt-get install -y zsh tmux 2>> err.log
}

install_ubuntu_gui() {
    # 安装GVim terminator
    sudo apt-get install -y vim-gnome terminator 2>> err.log

    # 安装 Chromium
    sudo apt-get install -y chromium-browser 2>> err.log

    # 关闭Ubuntu错误报告
    sudo sed -i 's/enabled=1/enabled=0/' /etc/default/apport
    sudo service apport restart

    sudo apt-get install -y ttf-wqy-microhei 2>> err.log

    sudo apt-get install -y ruby-dev 2>> err.log
}

install_fedora() {
    sudo yum install vim
}

system_shell=$SHELL
export SHELL="/bin/sh"

if [ `uname` = "Darwin"]
then
    install_mac_os
elif [ `which apt-get` ]
then
    install_ubuntu
elif [ `which yum` ]
then
    intall_fedora
fi

export SHELL=$system_shell
